sudo: false
install: true

language: java
jdk:
- openjdk8

env:
  global:
  - secure: 'KEvNRnrKoQFGln6QoqSH3qBC6H/2g9oGQGMKriqiq/YLJ6SI0ZLyEO9qUQGAmoMfw1WM6Hmu7e3p//9znc5hIWAIXPE57LkFn1z5iTqUKmAokCb2fqpoTCOkz0Lze2yVFqysNriXVGfptAckJwV3jeGiTzILDulBKOtvxxI5bZDr3leoXaBZ00XzHZGbGmWGAOc/YRiSGWrGXF+Rf8rJcOQeHjPWg7BsgVSMncHAqKuQk6QEVZB56VX3LXtgyr10P1UUU+GAO/XyQm0OrmPWUhdEe6nAZFGZaLGLNmi430ZqScH8F6vDTe9OYM/fJ/QYbb1BXaMX6Hr7modrUvEwn7w3Nb956BZC4LB2S6RNcZiLC3n/Bg8cMtLp6jfftisYhJLggjwcbDfSN97Oiq8PFCop9i+Okj7enupJ8lHAckFA2ACTgO0+750GEFmwQEFUSQvWHSgISpnsC77JAksPLuYriMNMnpM6/YIPm0DuIkHhfKxsTmRa5dNXjmKo/SHb4qz647CcUqUQVhngdvLYOeB2e6XiTYxDFg1OWkRC0SZUz6z0YeqOxckBAAzZOa2JYRl2/JyRqrA616QdS+EWRZt68RsQC7+JssbYWYf0rcT+GzyqXj8++xle2P5ER2tobgIMGjzWhhzTvPytyHfYBwmdMRDoM5hYKcVcgLnFNSE='
  - secure: 'Lmyo9gDJPHaM6j7Z98wPLFny2sXOgmBB94KcP/yngSyMWX3gy17ubGTJL724s60QxXIEyX2A+s+PKm066n9qPoJQ6ddGm3emrYdynZ663ZkAQT5LLH1ALB3iSabUb+x6lnAzYoTcg77X5KsUtu/GFxF8qDJ6NJ9F7L21hB+5uy3NeqcAdC7lSO6aA05zaXXHrwgY+3vTjNUDmKL7cZUqwrhw25XxbwHxPSwd0Wz5sXXvm5DlFnJd/1FadGTr9ZxXIemdq/gcPVOKr/8wstDxhe4TrF90Pgs7MP05D7LClZ5yx0pHFE/+GiuzScnppqgyT6MJJp807hT9cqjSbYktgHaYq4trGASwUd0LLUSuit6jxvb0QQCI8xIOEJlfIoiplIDEqBfYJYhaXwmAdFluAYuZxGGYLMHp1c9MgVHjQ3tbwOkYm5CAV2lHAIXhL6KC0r/DwcEFaN42UzEIDsjPTtmpTqu4rXr0WtMlUb8YpBuT4JYjFLTuJCNixwM3IGbQXWBU7RNzFF442e+rJnUO5ivut8bW7zOHoLG5nxFFnOhTLl0CljOmadTL4UyhmA/CCHZyLTeDUzZjWkmKnaAuh8RXuJFwnYOCTHSInweyTEna47QD62khdhu6LYkhSSPmPizm5KoJCNVn4pK951ae6Yx8IoXvEJB+RnP45XrH6hs='

addons:
  sonarcloud:
    organization: 'dmitriiserikov-github'
    token: $SONAR_TOKEN

stages:
- test
- deploy

jobs:
  include:
  - stage: test
    script: ./mvnw clean test -P dev
    name: 'Unit tests'
  - stage: test
    script: ./mvnw clean install -P integration-test
    name: 'Integration tests'
  - stage: test
    script: ./mvnw clean jacoco:prepare-agent install sonar:sonar -P sonar
    name: 'Sonar'
  - stage: deploy
    script: skip
    name: "Deploy to Heroku"
    deploy:
      provider: heroku
      api_key: $HEROKU_API_KEY
      app: money-transfer-service

after_success:
- bash <(curl -s https://codecov.io/bash)

cache:
  directories:
  - '$HOME/.m2/repository'
  - '$HOME/.sonar/cache'