micronaut:
    application:
        name: money-transfer-service

jackson:
    serialization:
        writeDatesAsTimestamps: false

processing:
    transactions:
          cron: 0 * * ? * *
          limit: 500