micronaut:
    application:
        name: money-transfer-service
    router:
        static-resources:
            swagger:
                paths: classpath:META-INF/swagger/

jackson:
    serialization:
        writeDatesAsTimestamps: false

processing:
    transactions:
          enabled: true
          cron: 0 * * ? * *
          limit: 500
    lockHolder:
          timeout: 5000

money:
    transfer:
          api:
              version: 1.0